<?php

namespace App\Enum;

class ApiError
{
    // Auth
    const USER_NOT_AUTHENTICATED = 'USER_NOT_AUTHENTICATED';
    const ACCESS_DENIED = 'ACCESS_DENIED';
    const EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED';
    const INVALID_CREDENTIALS = 'INVALID_CREDENTIALS';

    // User
    const USER_NOT_FOUND = 'USER_NOT_FOUND';
    const EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS';
    const INVALID_DATA = 'INVALID_DATA';
    const MISSING_PARAMETERS = 'MISSING_PARAMETERS';
    const INVALID_PASSWORD = 'INVALID_PASSWORD';
    const PASSWORD_TOO_SHORT = 'PASSWORD_TOO_SHORT';
    const VALIDATION_FAILED = 'VALIDATION_FAILED';
    const INVALID_TOKEN = 'INVALID_TOKEN';
    const TOKEN_EXPIRED = 'TOKEN_EXPIRED';
    const EMAIL_ALREADY_VERIFIED = 'EMAIL_ALREADY_VERIFIED';
    const USER_HAS_ORDERS = 'USER_HAS_ORDERS';
    const USER_HAS_SUBSCRIPTIONS = 'USER_HAS_SUBSCRIPTIONS';

    // Category
    const CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND';
    const CATEGORY_HAS_PRODUCTS = 'CATEGORY_HAS_PRODUCTS';
    const CATEGORY_HAS_CHILDREN = 'CATEGORY_HAS_CHILDREN';

    // Product
    const PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND';
    const PRODUCT_HAS_ORDERS = 'PRODUCT_HAS_ORDERS';

    // Order
    const ORDER_NOT_FOUND = 'ORDER_NOT_FOUND';
    const INVALID_QUANTITY = 'INVALID_QUANTITY';

    // Subscription
    const SUBSCRIPTION_NOT_FOUND = 'SUBSCRIPTION_NOT_FOUND';
    const SUBSCRIPTION_PLAN_NOT_FOUND = 'SUBSCRIPTION_PLAN_NOT_FOUND';
    const SUBSCRIPTION_PLAN_HAS_SUBSCRIPTIONS = 'SUBSCRIPTION_PLAN_HAS_SUBSCRIPTIONS';

    // Digital Content
    const DIGITAL_CONTENT_NOT_FOUND = 'DIGITAL_CONTENT_NOT_FOUND';
    const FILE_NOT_FOUND = 'FILE_NOT_FOUND';

    // Administrator
    const ADMINISTRATOR_NOT_FOUND = 'ADMINISTRATOR_NOT_FOUND';
    const NOT_AN_ADMINISTRATOR = 'NOT_AN_ADMINISTRATOR';
    const CANNOT_DELETE_LAST_ADMINISTRATOR = 'CANNOT_DELETE_LAST_ADMINISTRATOR';

    // Stripe / Payment
    const PAYMENT_ERROR = 'PAYMENT_ERROR';

    // Generic
    const INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';
    const NOT_FOUND = 'NOT_FOUND';
    const METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED';
    const BAD_REQUEST = 'BAD_REQUEST';
}
