apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: maison-epouvante-back-vault
  namespace: maison-epouvante
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: maison-epouvante-back-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Variables d'environnement normales (passthrough direct)
        APP_ENV: "{{ .APP_ENV }}"
        APP_SECRET: "{{ .APP_SECRET }}"
        DATABASE_URL: "{{ .DATABASE_URL }}"
        DATABASE_HOST: "{{ .DATABASE_HOST }}"
        DATABASE_PORT: "{{ .DATABASE_PORT }}"
        DATABASE_NAME: "{{ .DATABASE_NAME }}"
        DATABASE_USER: "{{ .DATABASE_USER }}"
        DATABASE_PASSWORD: "{{ .DATABASE_PASSWORD }}"
        JWT_PASSPHRASE: "{{ .JWT_PASSPHRASE }}"
        CORS_ALLOW_ORIGIN: "{{ .CORS_ALLOW_ORIGIN }}"
        MAILER_DSN: "{{ .MAILER_DSN }}"
        STRIPE_SECRET_KEY: "{{ .STRIPE_SECRET_KEY }}"
        DEFAULT_URI: "{{ .DEFAULT_URI }}"
        FRONTEND_URL: "{{ .FRONTEND_URL }}"
        # Clés JWT décodées depuis base64 pour montage fichier
        JWT_PRIVATE_KEY: "{{ .JWT_PRIVATE_KEY | b64dec }}"
        JWT_PUBLIC_KEY: "{{ .JWT_PUBLIC_KEY | b64dec }}"
  dataFrom:
    - extract:
        key: maison-epouvante/app
