name: PR 

on:
  pull_request:
    branches: [ main ]

jobs:
    code-quality:
        uses: ./.github/workflows/code-quality.yml
        

    test:
        needs: code-quality
        uses: ./.github/workflows/test.yml